<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0," />
  <script src="assets/js/jquery.min.js" type="text/javascript"></script>
  <title></title>
</head>
<?php //echo $this->getHeadHtml(); ?>
<body style="margin: 0px; padding: 0px;">
    <?php echo $this->getContentHtml(); ?>
</body>
</html>