<form action="index.php?controller=category_index&action=create" method="post">  
<div>
    <table  border="0">
        <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3> 
                        <?php echo 'Manage Customers'; ?>
                    </h3> 
                </td>
                <td>
                    <input type="submit" value="Create Category" name="createcategory">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td>
            </tr>
        </tbody>
    </table>
</div>

</form>
