<?php
    $database = Ccc::getModel('database');
    $category = Ccc::getModel("category");
    $row = $database->fetchAll("select * from category");
?>

    <table border='1'>
        
        <tr>
            <th></th>
            <th>Category Id</th>
            <th>Category name</th>
            <th>Status</th>
            <th>Created_date</th>
            <th>Updated_date</th>
            <th colspan=3>Action</th> 
        </tr>
<?php foreach($row as $records) : ?>
        <tr>
            <td><input name="check_single[]" value="<?php echo $cnt++ ?>" class="check_single input-checkbox" type="checkbox"> </td>
            <td> <?php echo $records['category_id'] ?> </td>
            <td> <?php echo $records['category_name'] ?>  </td>
            <td> <?php echo ($records['status'] == Model_Category::STATUS_YES?'Yes':'No') ?> </td> 
            <td> <?php echo $records['created_date'] ?> </td>
            <td> <?php echo $records['updated_date'] ?>  </td>
            <td><a href="index.php?controller=category_index&action=delete&deleteId=<?php echo $records['category_id']; ?> ">Delete</a></td> 
            <td><a href="index.php?controller=category_index&action=edit&editId=<?php echo $records['category_id']; ?> ">Edit</a></td> 
            <td><a href="index.php?controller=category_index&action=updateStatus&statusId=<?php echo $records['category_id']; ?>&status=<?php echo $records['status']; ?> "><?php echo ($records['status'] == Model_Category::STATUS_YES?'Enable':'Disable'); ?></a></td> 
        </tr>
<?php endforeach; ?>
   
</table>

