<form id="grid-search-form" action="index.php?controller=history_index&action=index" method="post">  
<?php $customer = $this->getCollection(); ?>
    <div class="vehicle-details">
        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                
                    <div class="form-group">
                        <label >Customer Name</label>
                        <input name="cust_name" type="text" class="form-control" >
                    </div>
                
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                
                    <div class="form-group">
                        <label >Mobile Number</label>
                        <input name="mobile_number" type="text" class="form-control" value="" >
                    </div>
                
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                    
                    <div class="form-group">
                        <label >Vehicle Number</label>
                        <input name="vehicle_number" type="text" class="form-control" value="" >
                    </div>
                    
            </div>
            <div class="col-md-2 col-sm-6 col-xs-12">
                    <button type="submit"><i class="fa fa-search" aria-hidden="true"></i>Search</button>
            </div>
        </div>
    </div> 
    <div class="veh-deta-table">
        <div class="veh-deta-main">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th align = "left">Customer Name</th>
                        <th align = "left">Mobile Number</th>
                        <th align = "center" width = "200">Vehicle Number</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(count($customer) > 0):?>
                        <?php foreach($customer as $_value):?>
                            <tr class="clickable-row" data-href="<?php echo "index.php?controller=bill_view&action=index&id=".$_value['id']?>">
                                <td><?php echo $_value["customer_name"];?></td>
                                <td><?php echo $_value["mobile_number"];?></td>
                                <td align = "center"><?php echo $_value["vehical_number"];?></td>
                            </tr>
                        <?php endforeach;?>
                    <?php endif;?>
                </tbody>
            </table>
        </div> 
    </div>
</form>
<style type="text/css">
    tr.clickable-row{
        cursor: pointer;
    }
</style>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        jQuery(".clickable-row").on('click', function() {
            window.location = jQuery(this).data("href");
        });
    });
</script>     