<?php $database = Ccc::getModel('database') ?>
<?php $customer = Ccc::getModel("customer") ?>
<?php $row = $database->fetchAll("select * from customer") ?>
<div id="grid-list"><input name="selectedIds" id="selectedIds" value="" type="hidden">
    <div>
        <div>
        <div class="ibox-content">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-example" >
                    <thead>
                        <tr>
                            <!-- <th></th> -->
                            <th>ID</th>
                            <th>First Name</th>
                            <th>Last Name </th>
                            <th>Email</th>
                            <th>Is_Enabled</th>
                            <th>Created_date</th>
                            <th colspan="3">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($row as $records): ?>
                            <tr class="even pointer">
                                <!-- <td class="a-center ">           
                                    <input name="check_single[]"  class="check_single input-checkbox" onclick="object.checkSingle(this)" type="checkbox">
                                </td> -->
                                <td align="center"> <?php echo $records['customer_id'] ?> </td>
                                <td align="left"> <?php echo $records['first_name'] ?>  </td>
                                <td align="left"> <?php echo $records['last_name'] ?>  </td>
                                <td align="left"> <?php echo $records['email'] ?>  </td>
                                <td align="left"> <?php echo ($records['is_enabled'] == Model_Customer::STATUS_YES?'Yes':'No') ?> </td> 
                                <td align="left"> <?php echo $records['created_date'] ?> </td>
                                <td align="left"><a href="index.php?controller=customer_index&action=delete&deleteId=<?php echo $records['customer_id']; ?> " class="Link" title="Delete"><img src="images/delete-icon.png" alt="delete"></a></td> 
                                <td align="left"><a href="index.php?controller=customer_index&action=edit&editId=<?php echo $records['customer_id']; ?> " class="Link" title="Edit"><img src="images/edit-2.png"></a></td> 
                                <td align="left"><a href="index.php?controller=customer_index&action=updateStatus&statusId=<?php echo $records['customer_id']; ?>&status=<?php echo $records['is_enabled']; ?> " class="Link" title="Status"><?php echo ($records['is_enabled'] == Model_Customer::STATUS_YES?'Enable':'Disable'); ?></a></td> 
                            </tr>
                        <?php endforeach; ?>
   
                    </tbody>
                </table>            
            </div>
       </div>
    </div>
</div>
</div>
<script>
    jQuery(document).ready(function(){
        jQuery('.dataTables-example').DataTable({
            pageLength: 25,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                 customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                }
                }
            ]

        });

    });

</script>
