<!-- <form id="grid-search-form" action="index.php?controller=customer_index&action=create" method="post">   -->
    <div class="vehicle-details">
        <h3>Services</h3>
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                
                    <div class="form-group">
                        <label >Services Name</label>
                        <input type="text" class="form-control" name="service_name" id="service_name">
                    </div>
                
            </div>
            <div class="col-md-2 col-sm-6 col-xs-12">
                    
                        <div class="form-group">
                            <label >Rate</label>
                            <input type="text" class="form-control" value="200" name="amount" id="amount">
                        </div>
                    
            </div>
            <div class="col-md-2 col-sm-6 col-xs-12">
               
                    <button id="addRow" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i>add</button>
                
            </div>
        </div>
    </div>
