<form name = "insert" action = "index.php?controller=service_index&action=saveinsession" method = "post" id="bill_service_form">
<?php $database = Ccc::getModel('database') ?>
<?php $customer = Ccc::getModel("customer") ?>
<?php $row = $database->fetchAll("select * from customer") ?>
<div class="veh-deta-table">
    <div class="veh-deta-main">
        <table class="table table-hover">
            <thead>
                <tr>
                <th align = "left">Services</th>
                <th align ="right" width = "100" >Amount</th>
                <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div> 
</div>
</form>
<script>
    jQuery(document).ready(function(){
        var i = 1;
        jQuery("#addRow").click(function(){
            var serviceName = jQuery("#service_name").val();
            var amount = jQuery("#amount").val();

            var markup = "<tr><td>"+serviceName+"<input type=text name=service["+i+"][service_name] value="+serviceName+" hidden></td><td align = right>"+amount+"<input type=text name=service["+i+"][amount] value="+amount+" hidden></td><td><button class=remove><i class='fa fa-trash' aria-hidden=true></i></button></td></tr>";
            
            $("table tbody").append(markup);
            i++;
        });
    });   
    jQuery(document).delegate('button.remove', 'click', function(e) {
        e.preventDefault();   
        jQuery(this).parents("tr").remove();
    });
</script>
