<div class="vehicle-details">
    <h3>Personal Details</h3>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            
                <div class="form-group">
                    <label >Parts Name</label>
                    <input type="text" class="form-control" name="part_name" id="part_name">
                </div>
            
        </div>
        <div class="col-md-2 col-sm-6 col-xs-12">
            
                <div class="form-group">
                    <label >Quantity</label>
                    <div class="select-box">
                        <select class="select-style" name="qty" id="qty">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                        </select>
                    </div>
                </div>
            
        </div>
        <div class="col-md-2 col-sm-6 col-xs-12">
            <div class="form-group">
                <label >Rate</label>
                <input type="text" class="form-control" value="200" name="rate" id="rate">
            </div>
        </div>
        <div class="col-md-2 col-sm-6 col-xs-12">
            <button type="button" id="addRow"><i class="fa fa-plus-circle" aria-hidden="true"></i>add</button>
        </div>
    </div>
</div>
