
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>MM Automobiles</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, shrink-to-fit=no">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap CSS -->
    
	<link rel="stylesheet" href="assets/css/font-awesome.css">
	<link rel="stylesheet" href="assets/css/bootstrap.css">
	<link rel="stylesheet" href="assets/css/select2.css">
	<link rel="stylesheet" href="assets/css/custom.css">
	<link rel="stylesheet" href="assets/css/font.css">
	<link rel="stylesheet" href="assets/css/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="assets/css/datatables.min.css"/>
	
	<script src="assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="assets/js/select2.js" type="text/javascript"></script>
    <script src="assets/js/custom.js" type="text/javascript"></script>
	<script type="text/javascript" src="assets/js/datatables.min.js"></script>
	<script type="text/javascript" src="assets/js/jquery-ui.js"></script>
	<script src="https://unpkg.com/react@15.3.0/dist/react.js"></script>
	<script src="https://unpkg.com/react-dom@15.3.0/dist/react-dom.js"></script>
	<script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
	<script src="https://unpkg.com/remarkable@1.7.1/dist/remarkable.min.js"></script>
	<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.34/dist/web3.js"></script>
	<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@1.0.0-beta.34/dist/web3.min.js"></script>
	
	
<?php if($this->getBlockCount()):?>
    <div style="width: 100%; background-color: gray; height: 100px;">
    <?php foreach($this->getBlocks() as $block): ?>
        <?php echo $block->toHtml(); ?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
    
</head>