<form name = "insert" action = "index.php?controller=customer_index&action=save" method = "post" >
<?php $customer = Ccc::getModel("customer") ?>
<?php $request = Ccc::getModel('request') ?>
<?php if($request->getParam('editId')): ?>
    <?php $customer->load($request->getParam('editId')) ?>
<?php endif; ?>
            <table  border = "1">                                           
                <input type = "hidden" name = "customer_id" value = "<?php echo $customer->customer_id; ?>"/>
                <th colspan = "2">
                    <h1>Customer</h1>
                </th>
                <tr>
                    <td>
                        <b>First Name :</b>
                    </td>
                    <td>
                        <input type = "text" name = "first_name" value = "<?php echo $customer->first_name; ?>"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Last Name :</b>
                    </td>
                    <td>
                        <input type = "text" name = "last_name" value = "<?php echo $customer->last_name; ?>"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>email :</b>
                    </td>
                    <td>
                        <input type = "text" name = "email" value = "<?php echo $customer->email; ?>" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Password :</b>
                    </td>
                    <td>
                        <input type = "text" name = "password" value = "<?php echo $customer->password; ?>"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <b>Is_Enabled :</b>
                    </td>
                    <td>
                        <?php $yes = $no = '' ?>
                        <?php if($product->is_enabled == 1):?>
                           <?php $yes = "selected" ?>
                        <?php elseif($product->is_enabled == 2): ?>
                            <?php $no = "selected" ?>    
                        <?php endif ?>
                    
                        <label>
                            <select name = "is_enabled">
                                <option value = "1" <?php echo $yes; ?> >Yes</option>
                                <option value = "2" <?php echo $no;?> >No</option>
                            </select>
                        </label>
                    </td>
                </tr>
                <tr>
                    <td align = "right">
                        <input type = "submit" value = "submit" name = "submit" />
                    </td>
                    <td>
                        &nbsp;
                    </td>
                </tr>
            </table>
</form>

