<form id="grid-search-form" action="index.php?controller=customer_index&action=create" method="post">  
    <div align="right">
        <table  border="0" >
            <tbody>
                <tr>
                    <td>
                        <input type="submit" value="Create Customer" name="createCustomer" class="btn btn-info btn-fill btn-wd">
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</form>                  