<div class="vehicle-details">
    <h3>Personal Details</h3>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <form >
                <div class="form-group">
                    <label >Customer Name</label>
                    <input type="text" class="form-control" >
                </div>
            </form>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <form >
                <div class="form-group">
                    <label >Mobile Number</label>
                    <input type="text" class="form-control" >
                </div>
            </form>
        </div>
    </div>
</div>
<div class="vehicle-details">
    <h3>Personal Details</h3>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <form >
                <div class="form-group">
                     <label >Vehicle Number</label>
                    <input type="text" class="form-control" >
                </div>
            </form>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <form>
                <div class="form-group brand">
                    <label>Select Brand</label>
                    <input type="text" class="form-control" placeholder="Search here" >
                    <button><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <form>
                <div class="form-group car-model">
                    <label>Model</label>
                    <input type="text" class="form-control" placeholder="Search here" >
                    <button><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
            </form>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <form >
                <div class="form-group">
                    <label >Additional Info</label>
                    <input type="text" class="form-control" >
                </div>
            </form>
        </div>
    </div>
</div>